config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :listings, only: [:index] do
    resources :requests, only: [:create, :update]
  end

  resources :stops, only: [:create]

  resources :items, only: [:new, :create]

  delete '/items/:id', to: 'items#destroy', as: "delete_item"

  get '/dashboard', to: 'pages#dashboard'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="external-links">
        <a href="https://github.com/whatTheDuck101" target="_blank">
            <i class="fab fa-github-square" ></i>
        </a>
        <a href="https://www.linkedin.com/in/elizabeth-creary-766b42131/" target="_blank">
            <i class="fab fa-linkedin"></i>
        </a>
    </div>
    <div class="awknowledgement">
        <p class="ui-designer">UI designed by <em>WhatTheDuck101</em></p>
        <p>Created by Team Travely Batch#188 Le Wagon. Group design: <a href="http://www.travely.club/" target="_blank">Travely.club</a></p>
        <p>Icons made by <a href="https://www.flaticon.com/authors/franco-averta" title="Franco Averta" target="_blank">Franco Averta</a> 
        from <a href="https://www.flaticon.com/" title="Flaticon" target="_blank">www.flaticon.com</a> 
        is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank" target="_blank">CC 3.0 BY</a>
        </p>
        <p>Banner Photo by STIL on Unsplash & Card photos by various Upsplash artists </p>
    </div>
</div>

app/views/shared/_index_modal.html.erb
<% current_listing = Listing.find_by(item: item) %>
<% common_dates =  Listing.intersection_dates(current_listing.stop.start_date, current_listing.stop.end_date, user_start_date, user_end_date)%>

<div class="modal fade" id="modal-item-id-<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">

    <div class="modal-content">
        <div class="modal-image" style="background-image: url('<%= cl_image_path item.photo %>')"></div>
      
        <div class="modal-information">
          <h5 class="modal-title"><%= item.name.capitalize %></h5>
          <h6>Details:</h6>
          <p><%= item.description %></p>
          <% if current_user != item.user %>
            <h6>Dates available for you:</h6>
            <p><%= common_dates[0].try(:strftime, "%b %e %a") %> - <%= common_dates[-1].try(:strftime, "%b %e %a") %></p>
          <% end %>
          <h6>Owner:</h6>
          <div class="owner-adv" style="background-image: url('<%= cl_image_path item.user.photo%>');"><p><%= item.user.first_name %></p></div>

        </div>
      <div class="modal-footer">
        <% if current_user == item.user %>
          <h6>You own this item</h6>
        <% elsif !item.listings.first.is_available %>
          <h6>Sorry, this is item is already taken</h6>
        <% elsif current_user.requested_already?(item) %>
          <h6>Request Sent</h6>
        <% else %>
          <%= link_to 'I want this!', listing_requests_path(current_listing), id:item.id, class: "want-button", method: :post, remote: true %>
        <% end %>
      </div>
      <button type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "luggage.png", id: "logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if current_user.stops.any? %>
        <%= link_to "See Items", listings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <%= link_to "Share Item", new_item_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo.file.nil? %>
            <%= image_tag "userprofile.png", class: "avatar dropdown-toggle", id: "navbar-bunker-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-bunker-menu", "data-toggle" => "dropdown" %>
          <% end%>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
</div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_receieved_request.erb
<% @listings.each do |listing| %>
  <div class="col-xs-10">
   <div class="request-card">
    <% if listing.requests != nil %>
     <% @recieved_requests = listing.requests %>
     <% @recieved_requests.each do |request| %>
          <div class="request-card-image" style="background-image: url('<%= cl_image_path listing.stop.photo %>')"><%= listing.stop.city %></div>
          <div class="request-card-content">
            <div> <%= cl_image_tag request.user.photo, class: "card-user avatar-large" %> <%= cl_image_tag request.listing.item.photo %></div>
            <div> <%= request.user.first_name %> has requested your <%= request.listing.item.name %></div>
            <div> you will both be in <%= listing.stop.city %> between </div>
          </div>
          <div class="flat-card-actions">
            <% if request.status == "pending"%>
              <%= link_to "Accept", listing_request_path(request.listing.id, request.id, { value: "accepted" }), class: 'btn btn-success', method: :patch %>
              <%= link_to "Decline", listing_request_path(request.listing.id, request.id, { value: "denied" }), class: 'btn btn-danger', method: :patch %>
            <% elsif request.status == "accepted" %>
              <p><em>You have accepted this request!</em> </p>
            <% elsif request.status == "denied" %>
              <p><em>You have denied this request!</em> </p>
            <% end %>
          </div>

   <% else %>
    <%= You havent received any request yet %>
  <% end %>
  </div>
 </div>
<% end %>




       <% @listings.each do |listing| %>

              <% if listing.requests != nil %>
                <% @recieved_requests = listing.requests %>
                <% @recieved_requests.each do |request| %>
                  <% if request.status == "pending"%>
                      <div class="message">
                        <div class="message-name">
                          <p><%= request.listing.item.name %></p>
                        </div>
                         <div class="message-body">
                          <p><em>Please confirm reservation from <%= request.user.first_name %></em> </p>

                         </div>

                         <%= cl_image_tag request.user.photo, class: "card-user avatar-large" %>

                           <div class="message-status">
                              <%= link_to "Accept", listing_request_path(request.listing.id, request.id, { value: "accepted" }), class: 'btn btn-success', method: :patch %>
                              <%= link_to "Decline", listing_request_path(request.listing.id, request.id, { value: "denied" }), class: 'btn btn-danger', method: :patch %>
                           </div>
                         </div>
                    <% elsif request.status == "accepted" %>
                        <div class="">
                        <div class="">
                          <p><%= request.listing.item.name %></p>
                        </div>
                         <div class="">
                          <p><em>You have accepted this request!</em> </p>
                         </div>

                         </div>
                    <% elsif request.status == "denied" %>
                        <div class="">
                        <div class="">
                          <p><%= request.listing.item.name %></p>
                        </div>
                         <div class="">
                          <p><em>You have denied this request!</em> </p>
                         </div>
                  <% end %>
                <% end %>
              <% end %>
            <%end %>