config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :listings, only: [:index] do
    resources :requests, only: [:create, :update]
  end

  resources :stops, only: [:create]

  resources :items, only: [:new, :create]

  delete '/items/:id', to: 'items#destroy', as: "delete_item"

  get '/dashboard', to: 'pages#dashboard'
end

app/views/pages/_form_stop.html.erb
<div id="form">
    <div class="home-form-title"></div>
    <div class="sim-form">
        <%= form_tag(stops_path, class: "go-right") do %>
        <div class="trip-fields">

            <div class="trip-field">
            <div class="focus-label">
                <div class="nested-label">City</div>
            </div>
            <div class="focus-label">
                <div class="nested-label">Start date</div>
            </div>
            <div class="focus-label">
                <div class="nested-label">End date</div>
            </div>
            <button class="hidden-x" disabled><i class="fas fa-times-circle"></i></button>
            </div>

            <div id="trip-field-1" class="trip-field">
                <%= text_field_tag('stops[1][city]', nil, :required => true, class: "nested-input city-size algolia-input", id: "city-input", placeholder: "Enter Destination" ) %>
                <%= date_field_tag('stops[1][start_date]', Date.today, :required => true, class: "nested-input date-size" ) %>
                <%= date_field_tag('stops[1][end_date]', Date.today + 7, :required => true, class: "nested-input date-size" ) %>
                <button class="hidden-x" disabled><i class="fas fa-times-circle"></i></button>
            </div>
        </div>
    </div>
    <p id="add-city">+add city</p>
    <%= submit_tag("Search", class: "search-button") %>
    <%= submit_tag("Share item", class: "share-button") %>
    <% end %>
</div>

app/views/pages/_information.html.erb
<div class="home-information">
    <div class="step">
        <div class="text">
            <h3>Step 1</h3>
            <h6><%= link_to  "Sign Up ", new_user_registration_path %></h6>
            <h6><%= link_to  "Log In",  user_session_path %></h6>
        </div>
    </div>
    <div class="step">
        <div class="text">
            <h3>Step 2: Add City</h3>
            <h6>Add the cities you're stopping in</h6>
            <h6>*first city stop must be filled out*</h6>
        </div>
    </div>
    <div class="step">
        <div class="text">
            <h3>Step 3: Search || Share</h3>
            <h6>Search for items by city</h6>
            <h6>Share items by city</h6>
        </div>
    </div>
</div>

app/views/pages/dashboard.html.erb
<div class = "container-index">
  <div class="row">
    <div class="col-xs-4">
      <div class="my-itinerary">
        <h2>My Itinerary</h2>
      </div>
      <div class="itinerary-bar-dash"></div>
      <% @stops.each do |stop| %>
        <div class="circle-city-container">
          <div class="circle circle-dash"></div>
          <div class="city-card">
            <div>
              <div class="stop-city"><strong><%= stop.city.capitalize %></strong></div>
              <div class="stop-dates"><%= stop.start_date.strftime("%b %d, %y") %> - <%= stop.end_date.strftime("%b %d, %y") %></div>
            </div>
            <% if !(stop.photo.file.nil?)%>
              <%= cl_image_tag stop.photo,height: 60, width: 60, crop: :scale, class: "city-adv" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-xs-8">
        
      <div class="tab-wrapper">
      <!-- Tab links -->
        <div class="tab dashboard-tabs">
          <button class="tablinks dashboard-tab" onclick="openCity(event, 'items')"><%= pluralize( "(#{@items.count}) Shared ", 'Item' )%></button>
          <button class="tablinks dashboard-tab" onclick="openCity(event, 'receieved')"><%= pluralize( "(#{@offers.count})", 'Offer' )%></button>
          <button class="tablinks dashboard-tab" onclick="openCity(event, 'sent')"><%= pluralize( "(#{@requests.count})", 'Requests')%></button>
        </div>
      </div>
      <!-- Tab content -->
      <div class="tabcontents">
        

        <div id="items" class="tabcontent">
          <% @items.each do |item| %>
            <div class="col-xs-4" id="item-<%= item.id %>">
              <div class="card">
                <div class="card-body">
                  <div class="card-img-top" style="background-image: url('<%= cl_image_path item.photo%>')"></div>
                  <p class="card-text name">
                    <% if item.name.length >= 20 %>
                      <%= item.name.first(20)%>...
                    <% else %>
                      <%= item.name %>
                    <%end%>
                  </p>
                  <% item_cities = item.listings.map {|listing| listing.stop.city.upcase} %>
                  <p class="card-text location"><strong><%= item_cities.join(" - ") %></strong></p>
                  <%= link_to 'x', delete_item_path(item.id), class: 'delete-button', method: :delete, remote: true, 
                  data: { confirm: "This will delete all listings for this item. Are you sure you like to delete this item?" } %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
       

        <div id="receieved" class="tabcontent">

          <% users_received_requests = current_user.received_requests %>

          <% if users_received_requests.empty? %>
            <h3 class="none">No offers recieved</h3>
          <% else %>
          <div class="offer-card">
              <% users_received_requests.each do |request| %>
                <div class="offers-card">
                  <div class="offers-card-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%,
                    rgba(0,36,61,0.6) 50%), url('<%= cl_image_path request.listing.stop.photo %>')">
                    <div class="banner-content">
                      <% city = request.listing.stop.city %>
                      <h2><%= city.capitalize %></h2>
                        <%= cl_image_tag request.user.photo, class: "image-match-avt user-photo-match"%>
                        <%= cl_image_tag request.listing.item.photo, class: "image-match-avt item-photo-match" %>
                    </div>
                  </div>
                  <div class="offers-card-content">
                    <div class="offers-card-content description">
                      <span class="text-var"><%= request.user.first_name %></span>
                      <span class="text">wants your</span>
                      <span class="text-var"><u><%= request.listing.item.name %></u></span>
                    </div>
                    <div class="offers-card-content dates">
                      <% common_dates = Listing.intersection_dates(request.listing.stop.start_date, request.listing.stop.end_date, request.user.stops.find_by(city:city).start_date, request.user.stops.find_by(city:city).end_date)%>
                      <span class="text">You will both be in </span>
                      <span class="text-var"><%= city.capitalize %></span>
                      <span class="text">between<span>
                      <p class="text-var"><i class="far fa-calendar-alt"></i> <strong><%= common_dates[0].strftime("%b %d, %Y") %> 
                        ----------------------
                        <%= common_dates[-1].strftime("%b %d, %Y") %></strong> <i class="far fa-calendar-alt"></i>
                      </p>
                    </div>
                    <div class="line"></div>
                    <div class="offer-card-footer">
                      <div class="request-card-actions offers-card-content">
                        <% if request.status == "pending"%>
                          <%= link_to "Accept", listing_request_path(request.listing.id, request.id, { value: "accepted" }), class: 'accept-button', method: :patch, remote: true %>
                          <%= link_to "Decline", listing_request_path(request.listing.id, request.id, { value: "denied" }), class: 'decline-button', method: :patch, remote: true %>
                        <% elsif request.status == "accepted" %>
                          <h5 class="status"><i class="fas fa-quote-left"></i>  You have accepted this offer!  <i class="fas fa-quote-right"></i></h5>
                        <% elsif request.status == "denied" %>
                          <h5 class="status"><i class="fas fa-quote-left"></i> You have denied this offer! <i class="fas fa-quote-right"></i></h5>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>

        <div id="sent" class="tabcontent">
          <div class="">
            <div class="row">
              <% if @requests.empty? %>
              <h3 class="none">No items requested</h3>
              <% end %>

              <% @requests.each do |request| %>
                <div class="col-xs-4">
                  <div class="card-request">
                    <div class="card-request-content header">
                        <%if request.listing.item.name.length >= 20 %>
                          <h6><%= request.listing.item.name.first(20)%>...</h6>
                        <% else %>
                          <h6><%= request.listing.item.name %></h6>
                        <%end%>
                      <%= cl_image_tag request.listing.item.user.photo, class: "user"%>
                      <span class="user-name"> OWNER <strong> <%= request.listing.item.user.first_name %> <%= request.listing.item.user.last_name %></strong></span>
                    </div>

                    <div class="request-card-content-img" style="background-image: url('<%= cl_image_path request.listing.item.photo %>')"></div>

                    <div class="request-card-content status">
                      <p class="text">REQUEST STATUS:</p>
                      <div class="request-card-actions">
                        <% if request.status == "pending" %>
                          <h5>Pending</h5>
                          <p class="date-create"><%= request.created_at.strftime("%c") %></p>
                        <% elsif request.status == "accepted" %>
                          <h5 class="accepted">Accepted!</h5>
                          <div class="empty-space"></div>
                        <% else %>
                          <h5>Sorry, denied.</h5>
                          <div class="empty-space"></div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>


<script>
function openCity(evt, tabName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the button that opened the tab
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
}

</script>

<%= javascript_pack_tag 'dashboard_select_tab' %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(17,157,164,0.9), rgba(0,36,61,0.6) 50%), url('<%= image_path 'banner.jpg'%>');">
  <div id="logo-home" style="background-image: url('<%= image_path 'luggage.png' %>');"></div>
  <div class="banner-content-home">
    <h1>Travely</h1>
    <h2>Light & Easy Travel</h2>
    <h3>By Sharing your Items with Others</h3>
  </div>
  <% if !user_signed_in? %>
    <section id="section03" class="demo">
      <a href="#form"><span></span>Start</a>
    </section>
  <% end %>
</div>

<% if !user_signed_in? %>
  <div class="container">
    <%= render  "form_stop" %>  
    <div class="line-home"></div>  
    <%= render  "information" %>
  </div>
<% end %>

<% if user_signed_in? %>

  <div class="container signed-in-container">
    <%= render  "form_stop" %>
  </div>
  <div class="container">
    <%= render  "information" %>
  </div>
<% end %>

<%= render  "shared/footer" %>

<%= javascript_pack_tag 'add_city' %>
<%= javascript_pack_tag 'nested_input_home' %>
<%= javascript_pack_tag 'algolia_search' %>